### ISSUE TITLE
[FEATURE] Clarify that the results are approximations

### ISSUE THREAD

**Issue by tvercaut** [masadcv/FastGeodis#11]
**Is your feature request related to a problem? Please describe.**
The current documentation is implicit about the fact that the computed distances are approximations.

**Describe the solution you'd like**
The documentation could clarify that the balance in this repo is towards speed rather than accuracy.

**Additional context**
It might also be good to say that for the specific case of Euclidean Distance Maps, exact results can be achieved with other packages (albeit not on necessarilly on GPU):
- https://github.com/seung-lab/euclidean-distance-transform-3d
- https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.distance_transform_edt.html
- https://www.tensorflow.org/addons/api_docs/python/tfa/image/euclidean_dist_transform

**Comment by masadcv** [comment]
Many thanks, good point! I will solve this tonight...

**Comment by masadcv** [comment]
I have added all links as references and the following text to main README to make it clear that the raster scan method is a balance towards performance:

> The raster scan based implementation provides a balance towards speed rather than accuracy of Geodesic distance transform and hence results in efficient hardware utilisation. On the other hand, in case of Euclidean distance transform, exact results can be achieved with other packages (albeit not on necessarilly on GPU) [6, 7, 8]
