### ISSUE TITLE
[FEATURE] Add link back to github in reads the docs

### ISSUE THREAD

**Issue by tvercaut** [masadcv/FastGeodis#23]
**Is your feature request related to a problem? Please describe.**
The link to teh source code currentlly does not feature prominently on https://masad.ml/FastGeodis/

**Describe the solution you'd like**
Something along the lines of:
- Add a simple "Source code" section in the sidebar menu
- Replace "view page source" in the top right by "improve this page"

**Additional context**
A random example of this:
https://pylops.readthedocs.io/en/stable/

This can maybe be implemented through `conf.py`:
https://sphinx-rtd-theme.readthedocs.io/en/stable/configuring.html#confval-vcs_pageview_mode
https://github.com/PyLops/pylops/blob/c5844c4a4b25cdb74a5cef12b926d6d91da20095/docs/source/conf.py#L121-L143

**Comment by masadcv** [comment]
Many thanks for the suggestion. I have updated the docs and moved to readthedocs hosting as well.

Will work a bit more on completing the missing sections...
