### ISSUE TITLE
[General Question] Threshold for Geodesic Distance

### ISSUE THREAD

**Issue by Zrrr1997** [masadcv/FastGeodis#37]
Hi there! First of all, this is a wonderful implementation and I have had a very pleasant experience so far. 

I have a general question of understanding regarding Geodesic Distances as a whole. I have applied your method to the MSD Spleen dataset and got good results when training the MONAI Label DeepEdit model (instead of using Gaussian Heatmaps as guidance, I replaced it with GeoDis maps). 

However, it required a lot of manual tuning of the threshold for the Geodesic Distance. I struggled to find a systematic and consistent way to justify my choice for such a threshold. It seems that [MIDeepSeg](https://arxiv.org/pdf/2104.12166.pdf) tackles this exact problem and the authors  state that other methods simply empirically find the optimal threshold value (i.e. you have to do a grid search and train multiple models). 

My question would be: Is there a systematic way to find this threshold or is it problem-specific and requires a grid search?

Here are some more images which describe my problem:
- Large threshold leads to few errors but also does not really cover the spleen fully
- Small threshold "bleeds out" into the background, eventually degrading to Euclidean Distance
![geo_th_exp](https://user-images.githubusercontent.com/40185241/207266484-0df9d049-73be-4cf5-9b51-9d5322acbd5f.png)

- Increasing the threshold minimizes the overlap with the background (error), but also minimizes the overlap with the spleen (gt)
![corr_err](https://user-images.githubusercontent.com/40185241/207267097-8f4c618f-0133-48b6-b102-99deacffef3d.png)

**Comment by masadcv** [comment]
Hi @Zrrr1997 

Interesting question and very encouraging initial results. 
I am unsure what you mean by thresholding here. I believe this may be related to your other question about `v`.

If you are referring to one of the parameters (I dont remember particularly if I used a thresholding in here) then the parameters do need fine-tunning and any such tunning might be problem specific. Of course there are ways to get around this, for example if you use exponential geodesic distances as proposed in MIDeepSeg, you may have much more stable distance maps which you can use for training DeepEdit. 

I am happy to discuss this in more details offline, please feel free to reach out on my kcl email and we can arrange to have a more detailed discussion around this.

**Comment by masadcv** [comment]
Closing this as I already had one-to-one discussion with you regarding the questions you have.
