### ISSUE TITLE
[FEATURE] Add an API to provide signed distance maps

### ISSUE THREAD

**Issue by tvercaut** [masadcv/FastGeodis#9]
**Is your feature request related to a problem? Please describe.**
In several applications, having a signed distance map is helpful. 

**Describe the solution you'd like**
Providing a simple API to get signed distance maps in FastGeodis would be great.

**Describe alternatives you've considered**
Compute two distance maps (one with the mask and another one with the inverted mask) and substract these

**Additional context**
https://github.com/Project-MONAI/MONAI/discussions/4603

**Comment by tvercaut** [comment]
Nice. Yes, that looks right. I assume there might be a way to optimise things by running the raster scans with `mask` and `1-mask` in parallel but this can be left for future improvements.

**Comment by masadcv** [comment]
Makes sense, yes let's look into it in future improvements!

**Comment by masadcv** [comment]
Closing this for now as it is addressed in #10 - we can reopen/look into improving this in future
